// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAas3J4nHABlVG0awJN9JUOYdbSSJy9CQ8',
    appId: '1:369631637049:web:b86850d0bac6fe365c67e8',
    messagingSenderId: '369631637049',
    projectId: 'chat-app-4d831',
    authDomain: 'chat-app-4d831.firebaseapp.com',
    storageBucket: 'chat-app-4d831.appspot.com',
    measurementId: 'G-D2YZW3VR7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2sDDhV2HF_gXTHn2HZc9ENfE41zIZQ3U',
    appId: '1:369631637049:android:94b2920eb615df735c67e8',
    messagingSenderId: '369631637049',
    projectId: 'chat-app-4d831',
    storageBucket: 'chat-app-4d831.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkip2DNcXCmX3zELlFyysyR6dt2x97weY',
    appId: '1:369631637049:ios:c3d37e6178e360cb5c67e8',
    messagingSenderId: '369631637049',
    projectId: 'chat-app-4d831',
    storageBucket: 'chat-app-4d831.appspot.com',
    iosClientId: '369631637049-jffcr36qgcai6hs9e1f5lisv0crrnlrs.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarChat',
  );
}
